export const niceInputMap = {
    'key_press': 'Key',
    'xinput_button': 'Button',
    'mouse_button': 'Mouse Click',
    'mouse_wheel': 'Mouse Wheel',
    'mode_shift': 'Mode Shift',
    'controller_action': 'Action Set',
    'SHOULDER_LEFT': 'LB',
    'SHOULDER_RIGHT': 'RB',
    'JOYSTICK_RIGHT': 'Right Stick Click',
    'JOYSTICK_LEFT': 'Left Stick Click',
    'TRIGGER_LEFT': 'Left Trigger',
    'TRIGGER_RIGHT': 'Right Trigger',
    'button_diamond': 'Face Buttons',
    'left_trackpad': 'Left Trackpad',
    'right_trackpad': 'Right Trackpad',
    'left_trigger': 'Left Trigger',
    'right_trigger': 'Right Trigger',
    'joystick': 'Left Stick',
    'right_joystick': 'Right Stick',
    'gyro': 'Gyro',
    'edge': 'Soft Press',
    'click': 'Click',
    'absolute_mouse': 'As Mouse',
    'joystick_move': 'Joystick Move',
    'joystick_mouse': 'As Joystick',
    'joystick_camera': 'Joystick Camera',
    'mouse_joystick': 'Mouse-like Joystick',
    'mouse_region': 'Mouse Region',
    'dpad': 'Directional Pad',
    'radial_menu': 'Radial Menu',
    'touch_menu': 'Touch Menu',

    '2dscroll': 'Directional Swipe',
    'scrollwheel': 'Scroll Wheel',
    'single_button': 'Single Button',
    'four_buttons': 'Button Pad',
    'trigger': 'Trigger',
    'switches': 'Switches',
    'hold_layer': 'Hold'
} as const;

// best guesses
export const gyroButtonFlags: Record<number, string> = {
    0: 'right_trackpad_touch',
    1: 'left_trackpad_touch',
    2: 'right_stick_touch',
    3: 'left_stick_touch',
    4: 'button_diamond_button_a',
    5: 'button_diamond_button_b',
    6: 'button_diamond_button_x',
    7: 'button_diamond_button_y',
    8: 'dpad_north',
    9: 'dpad_south',
    10: 'dpad_west',
    11: 'dpad_east',
    12: 'right_trackpad_click',
    13: 'left_trackpad_click',
    14: 'right_stick_click',
    15: 'left_stick_click',
    16: 'left_trigger_edge',
    17: 'left_trigger_click',
    18: 'right_trigger_edge',
    19: 'left_bumper',
    20: 'right_trigger_click',
    21: 'right_bumper',
    22: 'button_escape',
    23: 'right_stick_deflect',
    24: 'joystick_deflect',
    25: 'button_menu',
    30: 'left_stick_deflect',
    41: 'button_back_left_upper',
    42: 'button_back_right_upper',
    43: 'button_back_left',
    47: 'button_back_right'
};

export const defaultGyroButton: Record<string, string> = {
    controller_neptune: '5',
    controller_steamcontroller_gordon: '1',
    controller_ps4: '1',
    controller_ps5: '1',
    controller_ps5_edge: '1'
};

